name: "Set Issue URL Label"
on:
  workflow_dispatch:
  issues:
    types: [opened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: '[ {"keywords": ["https://", "https"], "labels": ["url"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
