name: Url Issue Labeller
on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  daily_standup:
    name: ""
    runs-on: ubuntu-latest
    steps:
    - uses: imjohnbo/issue-bot@v3
      with:
        assignees: ""
        labels: "url"
        title: ""
        pinned: false
        close-previous: false
        linked-comments: false
